default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  database: <%= ENV.fetch("DB_NAME") %>

development:
  <<: *default

test:
  <<: *default
  database: synresins_ess_test

production:
  <<: *default
  database: synresins_ess_production